stages: 
    - build 
    - test
default:
    image:
        name: "mcr.microsoft.com/dotnet/core/sdk:latest"

build: 
    stage: build
    
    script:
        - "dotnet build"
        - "ls -lh ./UnitTestProject1/bin/Debug/netcoreapp3.0/"
    artifacts:
        paths: 
            - "./TPSLRawDataSimulator/bin/Debug"
            - "./UnitTestProject1/bin/Debug"

test:
    stage: test
    beforescript:
        - "dotnet restore"
    script:
        - "cd ./UnitTestProject1/"
        - "dotnet test --no-build"
