stages: 
    - build 
    - test
default:
    image:
        name: "mcr.microsoft.com/dotnet/core/sdk:latest"

build: 
    stage: build
    
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "dotnet test"
